API/urls.py
from django.conf.urls import url
from . import views

app_name = 'API'

urlpatterns = [

    # prende le informazioni di un utente
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET
    url(r'utenti/profilo/(?P<pk>[0-9]+)/$', views.userInfoLogin.as_view(), name='API-user-info'),

    # prende le informazioni dell'utente che ha richiamato l'api e ne permette la modifica
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET / PUT - serve essere loggati
    url(r'utenti/profilo/$', views.selfUserInfoLogin.as_view(), name='API-self-user-info'),

    # completa la registrazione per un petsitter
    # /API/utenti/registra/petsitter metodi ammessi :PUT
    url(r'utenti/registra/petsitter$', views.completaRegPetsitter.as_view(), name='API-registra-petsitter'),

    # completa la registrazione per un utente normale
    # /API/utenti/registra/utente-normale metodi ammessi :PUT
    url(r'utenti/registra/utente-normale$', views.completaRegUtentenormale.as_view(),
        name='API-registra-utente-normale'),

    # visualizza gli annunci
    # /API/annunci/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/$', views.listaAnnunci.as_view(), name='API-lista-annunci'),

    # filtra gli annunci
    # /API/annunci/filtra-per-dist-decrescente/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/ordina/(?P<animale>[A-Za-z0-9*èòàùì]+)/(?P<ordinamento>[A-Za-z0-9*èòàùì]+)/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/$',
        views.ordinaAnnunci.as_view(),
        name='API-ordina-annunci-animale-distanza-utente'),

    # osserva l'annuncio nel dettaglio e ne permette anche l'eliminazione o modifica purchè chi la chiama è
    # colui che lo ha scritto
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/dettagli/$', views.dettaglioAnnuncio.as_view(), name='API-dettaglio-annuncio'),

    # restituisce solamente gli annunci di un utente avente un determinato ID
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/(?P<pk>[0-9]+)/elenco/$', views.elencoAnnunciUtente.as_view(), name='API-elenco-annunci-utente'),

    # inserisce un nuovo annuncio
    # /API/annunci/nuovo/
    url(r'annunci/nuovo/$', views.inserisciAnnuncio.as_view(), name='API-nuovo-annuncio'),

    # accetta un annuncio avente ID comunicato via link
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/accetta/$', views.accettaAnnuncio.as_view(), name='API-accetta-annuncio'),

    # restituisce gli annunci accettati dall'utente che richiama questo link
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/$', views.calendarioUtente.as_view(), name='API-calendario-utente'),

    # restituisce gli annunci accettati dall'utente che richiama questo link filtrati per animale e validità
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/filtra/(?P<animale>[A-Za-z0-9*]+)/$',
        views.calendarioUtenteConFiltro.as_view(),
        name='API-calendario-utente-con-filtro-annunci'),

    # cerca l'utente per username
    # /API/utenti/cerca/<char:name>' GET : tutti gli utenti
    url(r'utenti/cerca/(?P<name>[A-Za-z0-9èòàùì]+)/$', views.cercaUtente.as_view(), name='API-cerca-utente'),

    # classifica utenti
    # /API/utenti/classifica/<tipo utente>/<criterio>/  metodi ammessi  GET : a tutti gli utenti
    url(r'utenti/classifica/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/(?P<criterio>[A-Za-z0-9èòàùì]+)/$',
        views.classificaUtenti.as_view(),
        name='API-classifica-utenti'),

    # Cassa Pet Coins utenti
    # /API/utenti/cassa/  metodi ammessi  PUT : ai soli utenti loggati
    url(r'utenti/cassa/$',
        views.modificaPetCoins.as_view(),
        name='API-petcoins-utenti'),

    # recensisci utenti
    # recensioni/nuova/<utente_recensito>/ metodi ammessi  POST : a tutti gli utenti
    # in automatico verrà settato il nickname di chi scrive la recensione
    url(r'recensioni/nuova/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensisciUtente.as_view(),
        name='API-recensisci-utenti'),

    # recensioni di un utente
    # /API/recensioni/ricevute/<utente>/  metodi ammessi  GET : a tutti gli utenti
    url(r'recensioni/ricevute/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensioniRicevute.as_view(),
        name='API-lista-recensioni-utente'),

    # contattaci
    # /API/annunci/nuovo/ metodi ammessi  POST : a tutti gli utenti loggati
    url(r'contattaci/$', views.contattaciInPrivato.as_view(), name='API-contattaci'),
]

Animal'sCare/urls.py
from main import views as main_views
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^annunci/', include('annunci.urls')),
    url(r'^contattaci/', include('contattaci.urls')),
    url(r'^utenti/', include('utenti.urls')),
    url(r'^recensioni/', include('recensioni.urls')),
    url(r'^api/', include('API.urls')),
    url('', include('social_django.urls', namespace='social')),

    url("api-auth/", include("rest_framework.urls")),
    url("api/rest-auth/", include("rest_auth.urls")),
    url("api/rest-auth/registration/", include("rest_auth.registration.urls")),

    # url('accounts/', include('allauth.urls')), # <--
]

handler404 = main_views.handler404
handler500 = main_views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annunci/urls.py
from django.conf.urls import url
from . import views

app_name = 'annunci'

urlpatterns = [

    # /annunci/
    url(r'^$', views.lista_annunci, name='lista_annunci'),

    # /annunci/nuovo/
    url(r'nuovo/$', views.inserisci_annuncio, name='inserisci_annuncio'),

    # /annunci/#annuncio/dettagli/
    url(r'(?P<oid>[0-9]+)/dettagli/$', views.dettagli_annuncio, name='dettagli_annuncio'),

    # /annunci/#annuncio/modifica/
    url(r'(?P<oid>[0-9]+)/modifica/$', views.modifica_annuncio, name='modifica_annuncio'),

    # /annunci/#annuncio/elimina/
    url(r'(?P<oid>[0-9]+)/elimina/$', views.elimina_annuncio, name='elimina_annuncio'),

    # /annunci/#annuncio/elimina/conferma/
    url(r'(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_annuncio_conferma, name='elimina_annuncio_conferma'),

    # /annunci/#annuncio/accetta/
    url(r'(?P<oid>[0-9]+)/accetta/$', views.accetta_annuncio, name='accetta_annuncio'),

    # /annunci/#annuncio/accetta/conferma/
    url(r'(?P<oid>[0-9]+)/accetta/conferma/$', views.conferma_annuncio, name='conferma_annuncio'),

    # /annunci/calendario/
    url(r'calendario/$', views.calendario, name='calendario'),

    # /annunci/@username/elenco
    url(r'(?P<username>\w+)/elenco/$', views.annunci_di_utente, name='annunci_di_utente'),
]

recensioni/urls.py
from django.conf.urls import url
from . import views

app_name = 'recensioni'

urlpatterns = [

    # /recensioni/nuova/#user_recensito/
    url(r'nuova/(?P<oid>[0-9]+)/$', views.nuova_recensione, name='nuova_recensione'),

    # /recensioni/ricevute/@username/
    url(r'ricevute/(?P<username>\w+)/$', views.recensioni_ricevute, name='recensioni_ricevute'),
]

utenti/urls.py
from django.conf.urls import url
from . import views

app_name = 'utenti'

urlpatterns = [

    # /utenti/login/
    url(r'login/$', views.login_user, name='utenti_login'),

    # /utenti/registrazione/
    url(r'registrazione/$', views.registrazione, name='registrazione'),

    # /utenti/registrazione/normale
    url(r'registrazione/normale$', views.registrazione_normale, name='registrazione_normale'),

    # /utenti/registrazione/petsitter
    url(r'registrazione/petsitter$', views.registrazione_petsitter, name='registrazione_petsitter'),

    # /utenti/logout/
    url(r'logout/$', views.logout_user, name='utenti_logout'),

    # /utenti/profilo/#user
    url(r'profilo/(?P<oid>[0-9]+)/$', views.view_profile, name='view_profile'),

    # /utenti/profilo/#user/modifica/
    url(r'profilo/(?P<oid>[0-9]+)/modifica/$', views.edit_profile, name='edit_profile'),

    # /utenti/profilo/#user/elimina/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/$', views.elimina_profilo, name='elimina_profilo'),

    # /utenti/profilo/#user/elimina/conferma/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_profilo_conferma, name='elimina_profilo_conferma'),

    # /utenti/cassa/
    url(r'cassa/$', views.cassa, name='cassa'),

    # /utenti/classifica/
    url(r'classifica/$', views.classifica, name='classifica'),

    # /utenti/cerca/
    url(r'cerca/$', views.cerca_utenti, name='cerca_utenti'),

    # /check_username/?username=john
    url(r'check_username/$', views.check_username, name='check_username'),

    # /utenti/scegli_profilo/
    url(r'scegli_profilo/$', views.scelta_profilo_oauth, name='scelta_profilo_oauth'),

    # /utenti/oauth_petsitter
    url(r'oauth_petsitter/$', views.oauth_petsitter, name='oauth_petsitter'),

    # /utenti/oauth_normale
    url(r'oauth_normale/$', views.oauth_normale, name='oauth_normale'),
]

annunci/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings


class Annuncio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    user_accetta = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user_accetta')

    annuncio_petsitter = models.BooleanField(default=True)   # Indica se l'annuncio e' stato inserito da un petsitter
    titolo = models.CharField(max_length=100)
    sottotitolo = models.CharField(max_length=100)
    descrizione = models.CharField(max_length=250)
    pet_coins = models.PositiveIntegerField(default=0)
    pet = models.CharField(max_length=50)
    data_inizio = models.DateTimeField(default=timezone.now)
    data_fine = models.DateTimeField(default=timezone.now)
    logo_annuncio = models.FileField(null=True, default='', blank=True)

    def logo_annuncio_or_default(self, default_path=static("/images/annuncio_default.jpg")):
        if self.logo_annuncio:
            return settings.MEDIA_URL + str(self.logo_annuncio)
        return default_path

    class Meta:
        verbose_name = 'Annuncio'
        verbose_name_plural = "Annunci"

    def __str__(self):
        return self.titolo


class Servizio(models.Model):
    annuncio = models.ForeignKey(Annuncio, on_delete=models.CASCADE)
    passeggiate = models.BooleanField(default=False)
    pulizia_gabbia = models.BooleanField(default=False)
    ore_compagnia = models.BooleanField(default=False)
    cibo = models.BooleanField(default=False)
    accompagna_dal_vet = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Servizio'
        verbose_name_plural = "Servizi"

annunci/forms.py
from django import forms
from .models import Annuncio, Servizio
from datetime import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import magic
import re
MIME_TYPES = ['image/jpeg', 'image/png']


class AnnuncioForm(forms.ModelForm):
    required_css_class = 'required'
    descrizione = forms.CharField(widget=forms.Textarea)
    data_inizio = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    data_fine = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    scelta_animali = (('Cane', 'Cane'), ('Gatto', 'Gatto'), ('Coniglio', 'Coniglio'), ('Volatile', 'Volatile'),
                      ('Rettile', 'Rettile'), ('Altro', 'Altro'))
    pet = forms.ChoiceField(choices=scelta_animali)
    logo_annuncio = forms.ImageField(required=False)

    class Meta:
        model = Annuncio
        fields = ['titolo', 'sottotitolo', 'descrizione', 'data_inizio', 'data_fine',
                  'pet', 'pet_coins', 'logo_annuncio']

    def clean_titolo(self):
        # controllo titolo
        if not re.match("^[A-Za-z0-9 .,'èòàùì]+$", self.cleaned_data['titolo']):
            raise ValidationError(_('Errore: il titolo può contenere solo lettere, numeri e spazi.'))
        if not (1 <= len(self.cleaned_data['titolo']) <= 95):
            raise ValidationError(_('Errore: il titolo deve avere lunghezza fra 1 e 95 caratteri.'))
        return self.cleaned_data['titolo']

    def clean_sottotitolo(self):
        # controllo sottotitolo
        if not re.match("^[A-Za-z0-9 ,.')èòàùì]+$", self.cleaned_data['sottotitolo']):
            raise ValidationError(_('Errore: il sottotitolo può contenere solo lettere, '
                                    'numeri, punti, virgole e spazi.'))
        if not (1 <= len(self.cleaned_data['sottotitolo']) <= 95):
            raise ValidationError(_('Errore: il sottotitolo deve avere lunghezza fra 1 e 95 caratteri.'))
        return self.cleaned_data['sottotitolo']

    def clean_descrizione(self):
        # controllo descrizione
        if not re.match("^[A-Za-z0-9 .,'èòàùì]+$", self.cleaned_data['descrizione']):
            raise ValidationError(_('Errore: la descrizione può contenere solo lettere, '
                                    'numeri, punti, virgole e spazi.'))
        if not (1 <= len(self.cleaned_data['descrizione']) <= 245):
            raise ValidationError(_('Errore: il titolo deve avere lunghezza fra 1 e 245 caratteri.'))
        return self.cleaned_data['descrizione']

    def clean_data_inizio(self):
        # controllo se data inizio < data_fine e se data_inizio e data_fine > adesso
        data_inizio = self.cleaned_data['data_inizio']
        if data_inizio < datetime.now():
            raise ValidationError(_('Errore: la data di inizio non può essere nel passato.'))
        return self.cleaned_data['data_inizio']

    def clean_data_fine(self):
        # controllo se data inizio < data_fine e se data_inizio e data_fine > adesso
        data_inizio = self.cleaned_data['data_inizio']
        data_fine = self.cleaned_data['data_fine']
        if data_inizio >= data_fine:
            raise ValidationError(_('Errore: la data di inizio deve avvenire prima della data di '
                                    'fine e non possono essere uguali.'))
        if data_fine < datetime.now():
            raise ValidationError(_('Errore: la data di fine non può essere nel passato.'))
        return self.cleaned_data['data_fine']

    def clean_pet_coins(self):
        # controllo pet_coins
        if not re.match("^[0-9]+$", str(self.cleaned_data['pet_coins'])):
            raise ValidationError(_('Errore: il campo pet coins può contenere solo numeri.'))
        if not (1 <= int(self.cleaned_data['pet_coins']) <= 100000):
            raise ValidationError(_('Errore: il valore in pet coins deve essere compreso tra 1 e 100000.'))
        return self.cleaned_data['pet_coins']

    def clean_logo_annuncio(self):
        files = self.files.get('logo_annuncio')
        if files is not None:
            file_size = files.size
            limit_MB = 5
            if file_size > limit_MB * 1024 * 1024:
                raise ValidationError("La dimensione massima per le immagini è %s MB" % limit_MB)

            file_type = magic.from_buffer(files.read(), mime=True)
            if file_type not in MIME_TYPES:
                raise forms.ValidationError(_("file non supportato."))
            return files
        return None


class ServizioForm(forms.ModelForm):
    class Meta:
        model = Servizio
        fields = ['passeggiate', 'pulizia_gabbia', 'ore_compagnia', 'cibo', 'accompagna_dal_vet']

annunci/templates/annunci/conferma_annuncio.html
{% extends base_template %}
{% block title %}Animal'sCare - Conferma{% endblock %}
{% block annunci_active %}active{% endblock %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h4>Accetti l'annuncio dell'utente <a href="{% url 'utenti:view_profile' oid=annuncio.user.pk %}" >
                                        {{ annuncio.user.username }}</a>&nbsp?</h4>
                        <a href="{% url 'annunci:dettagli_annuncio' oid=annuncio.pk %}" class="btn btn-primary">Indietro</a>&nbsp;&nbsp;
                        <a href="{% url 'annunci:accetta_annuncio' oid=annuncio.pk %}" class="btn btn-primary">Conferma</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

annunci/templates/annunci/dettagli_annuncio.html
{% extends base_template %}
{% block title %}Animal'sCare - Dettagli annuncio{% endblock %}
{% block annunci_active %}active{% endblock %}
{% load staticfiles %}
{% load nel_futuro %}

{% block body %}
<script type="text/javascript" src="{% static 'map.js' %}"></script>
<div class="container">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="">
                        <div><img src="{{ annuncio.logo_annuncio_or_default }}" alt="bootsnipp"
                                              class="img-rounded img-responsive"></div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">{{ annuncio.titolo }}</h3>

                    <div id="container" class="price h3 text-warning">
                        <p class="price-detail-wrap">
                            <span class="price h3 text-warning">
                                <div class="inline-block">
                                    <span class="num">{{ annuncio.pet_coins }}</span>
                                </div>
                                <div class="inline-block">
                                    <span class="currency"><img alt = "pet coins"
                                                                src="{% static 'images/pet_coin.png' %}"
                                                                class="img-responsive" style="width: 50%; height: 50%"></span>
                                </div>
                            </span>
                        </p>
                    </div>

                    <dl class="item-property">
                        <dt>Sottotitolo</dt>
                        <dd><p>{{ annuncio.sottotitolo }}</p></dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Descrizione</dt>
                        <dd>{{ annuncio.descrizione }}</dd>
                    </dl>
                    <dl class="param param-feature">
                        <div class="inline-block">
                            <dt>Pubblicato da</dt>
                        </div>&nbsp;
                        <div class="inline-block">
                            <dd><a href="{% url 'utenti:view_profile' oid=annuncio.user.pk %}" >
                                {{ annuncio.user.username }}</a>&nbsp;
                                {% if annuncio_profilo.pet_sitter %}
                                    (petsitter)
                                {% else %}
                                    (utente normale)
                                {% endif %}
                            </dd>
                        </div>
                    </dl>
                    {% if annuncio.user_accetta %}
                        <dl class="param param-feature">
                            <div class="inline-block">
                                <dt>Accettato da</dt>
                            </div>&nbsp;
                            <div class="inline-block">
                                <dd><a href="{% url 'utenti:view_profile' oid=annuncio.user_accetta.pk %}" >
                                    {{ annuncio.user_accetta.username }}</a>&nbsp;
                                {% if annuncio_accetta_profilo.pet_sitter %}
                                    (petsitter)
                                {% else %}
                                    (utente normale)
                                {% endif %}
                                </dd>
                            </div>
                        </dl>
                    {% endif %}
                    <dl class="param param-feature">
                        <dt>Pet</dt>
                        <dd>{{ annuncio.pet }}</dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Data inizio</dt>
                        <dd>{{ annuncio.data_inizio | date:"d/m/Y" }} {{ annuncio.data_inizio | time:"H:i" }}</dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Data fine</dt>
                        <dd>{{ annuncio.data_fine | date:"d/m/Y"}} {{ annuncio.data_fine | time:"H:i" }}</dd>
                    </dl>

                    <dl class="param param-feature">
                        <dt>Posizione&nbsp;&nbsp;<input id="mappa-btn" type="button" onclick="myFunction()" value="Mostra mappa" style="font-weight: normal"></dt>
                        <dd>
                            <div id="mappa-div" style="display: none">
                                <iframe width="300" height="250" frameborder="0" style="border:0"
                                        src="https://www.google.com/maps/embed/v1/search?q={{ annuncio_profilo.indirizzo }}%20{{ annuncio_profilo.citta }}%20{{ annuncio_profilo.provincia }}%20{{ annuncio_profilo.regione }}&key=AIzaSyA6GQs9IyXUWEBu6vDvlKteuM0AReR4Nag"
                                        allowfullscreen></iframe>
                            </div>
                        </dd>
                    </dl>

                    <hr>
                    <div class="row">
                        <div class="col-sm-10">
                            <dl class="param param-inline">
                                <dt>Servizi richiesti</dt>
                                <dd>
                                    <input type="checkbox" name="passeggiate"
                                            {% if annuncio_servizi.passeggiate %}
                                                checked
                                            {% endif %}
                                           disabled="disabled"> Passeggiate &nbsp;
                                    <input type="checkbox" name="pulizia_gabbia"
                                                {% if annuncio_servizi.pulizia_gabbia %}
                                                    checked
                                                {% endif %}
                                               disabled="disabled"> Pulizia gabbia &nbsp;
                                    <input type="checkbox" name="ore_compagnia"
                                                {% if annuncio_servizi.ore_compagnia %}
                                                    checked
                                                {% endif %}
                                               disabled="disabled"> Ore di compagnia <br>
                                    <input type="checkbox" name="cibo"
                                                {% if annuncio_servizi.cibo %}
                                                    checked
                                                {% endif %}
                                               disabled="disabled"> Dare da mangiare &nbsp;
                                    <input type="checkbox" name="accompagna_dal_vet"
                                                {% if annuncio_servizi.accompagna_dal_vet %}
                                                    checked
                                                {% endif %}
                                               disabled="disabled"> Accompagna dal veterinario
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <hr>
                    {% if user is not None and user.id is not None %}
                        {% if user.id != annuncio_utente.id %}
                            {% if user_profile.pet_sitter != annuncio_profilo.pet_sitter and annuncio.user_accetta is None %}
                                <a href="{% url 'annunci:conferma_annuncio' oid=annuncio.pk %}" class="btn btn-primary">Accetta annuncio</a>
                            {% endif %}
                        {% else %}
                            {% if not annuncio.user_accetta %}
                                <a href="{% url 'annunci:modifica_annuncio' oid=annuncio.pk %}" class="btn btn-primary">Modifica annuncio</a>
                                <a href="{% url 'annunci:elimina_annuncio' oid=annuncio.pk %}" class="btn btn-danger">Elimina annuncio</a>
                            {% endif %}
                        {% endif %}

                        {% if annuncio.user_accetta and not annuncio.data_fine|nel_futuro %}
                            <a href="{% url 'annunci:elimina_annuncio' oid=annuncio.pk %}" class="btn btn-danger">Elimina annuncio</a>
                        {% endif %}
                    {% endif %}
                </article>
            </aside>
        </div>
    </div>
</div>

{% endblock %}

annunci/templates/annunci/elimina_annuncio.html
{% extends base_template %}
{% block title %}Animal'sCare - Elimina annuncio{% endblock %}
{% block annunci_active %}active{% endblock %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h4>Confermi di voler eliminare l'annuncio?</h4>

                        <a href="{% url 'annunci:dettagli_annuncio' oid=annuncio.pk %}" class="btn btn-primary">Indietro</a>&nbsp;&nbsp;
                        <a href="{% url 'annunci:elimina_annuncio_conferma' oid=annuncio.pk %}" class="btn btn-danger">Conferma</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}