API/urls.py
from django.conf.urls import url
from . import views

app_name = 'API'

urlpatterns = [

    # prende le informazioni di un utente
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET
    url(r'utenti/profilo/(?P<pk>[0-9]+)/$', views.userInfoLogin.as_view(), name='API-user-info'),

    # prende le informazioni dell'utente che ha richiamato l'api e ne permette la modifica
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET / PUT - serve essere loggati
    url(r'utenti/profilo/$', views.selfUserInfoLogin.as_view(), name='API-self-user-info'),

    # completa la registrazione per un petsitter
    # /API/utenti/registra/petsitter metodi ammessi :PUT
    url(r'utenti/registra/petsitter$', views.completaRegPetsitter.as_view(), name='API-registra-petsitter'),

    # completa la registrazione per un utente normale
    # /API/utenti/registra/utente-normale metodi ammessi :PUT
    url(r'utenti/registra/utente-normale$', views.completaRegUtentenormale.as_view(),
        name='API-registra-utente-normale'),

    # visualizza gli annunci
    # /API/annunci/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/$', views.listaAnnunci.as_view(), name='API-lista-annunci'),

    # filtra gli annunci
    # /API/annunci/filtra-per-dist-decrescente/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/ordina/(?P<animale>[A-Za-z0-9*èòàùì]+)/(?P<ordinamento>[A-Za-z0-9*èòàùì]+)/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/$',
        views.ordinaAnnunci.as_view(),
        name='API-ordina-annunci-animale-distanza-utente'),

    # osserva l'annuncio nel dettaglio e ne permette anche l'eliminazione o modifica purchè chi la chiama è
    # colui che lo ha scritto
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/dettagli/$', views.dettaglioAnnuncio.as_view(), name='API-dettaglio-annuncio'),

    # restituisce solamente gli annunci di un utente avente un determinato ID
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/(?P<pk>[0-9]+)/elenco/$', views.elencoAnnunciUtente.as_view(), name='API-elenco-annunci-utente'),

    # inserisce un nuovo annuncio
    # /API/annunci/nuovo/
    url(r'annunci/nuovo/$', views.inserisciAnnuncio.as_view(), name='API-nuovo-annuncio'),

    # accetta un annuncio avente ID comunicato via link
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/accetta/$', views.accettaAnnuncio.as_view(), name='API-accetta-annuncio'),

    # restituisce gli annunci accettati dall'utente che richiama questo link
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/$', views.calendarioUtente.as_view(), name='API-calendario-utente'),

    # restituisce gli annunci accettati dall'utente che richiama questo link filtrati per animale e validità
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/filtra/(?P<animale>[A-Za-z0-9*]+)/$',
        views.calendarioUtenteConFiltro.as_view(),
        name='API-calendario-utente-con-filtro-annunci'),

    # cerca l'utente per username
    # /API/utenti/cerca/<char:name>' GET : tutti gli utenti
    url(r'utenti/cerca/(?P<name>[A-Za-z0-9èòàùì]+)/$', views.cercaUtente.as_view(), name='API-cerca-utente'),

    # classifica utenti
    # /API/utenti/classifica/<tipo utente>/<criterio>/  metodi ammessi  GET : a tutti gli utenti
    url(r'utenti/classifica/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/(?P<criterio>[A-Za-z0-9èòàùì]+)/$',
        views.classificaUtenti.as_view(),
        name='API-classifica-utenti'),

    # Cassa Pet Coins utenti
    # /API/utenti/cassa/  metodi ammessi  PUT : ai soli utenti loggati
    url(r'utenti/cassa/$',
        views.modificaPetCoins.as_view(),
        name='API-petcoins-utenti'),

    # recensisci utenti
    # recensioni/nuova/<utente_recensito>/ metodi ammessi  POST : a tutti gli utenti
    # in automatico verrà settato il nickname di chi scrive la recensione
    url(r'recensioni/nuova/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensisciUtente.as_view(),
        name='API-recensisci-utenti'),

    # recensioni di un utente
    # /API/recensioni/ricevute/<utente>/  metodi ammessi  GET : a tutti gli utenti
    url(r'recensioni/ricevute/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensioniRicevute.as_view(),
        name='API-lista-recensioni-utente'),

    # contattaci
    # /API/annunci/nuovo/ metodi ammessi  POST : a tutti gli utenti loggati
    url(r'contattaci/$', views.contattaciInPrivato.as_view(), name='API-contattaci'),
]

Animal'sCare/urls.py
from main import views as main_views
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^annunci/', include('annunci.urls')),
    url(r'^contattaci/', include('contattaci.urls')),
    url(r'^utenti/', include('utenti.urls')),
    url(r'^recensioni/', include('recensioni.urls')),
    url(r'^api/', include('API.urls')),
    url('', include('social_django.urls', namespace='social')),

    url("api-auth/", include("rest_framework.urls")),
    url("api/rest-auth/", include("rest_auth.urls")),
    url("api/rest-auth/registration/", include("rest_auth.registration.urls")),

    # url('accounts/', include('allauth.urls')), # <--
]

handler404 = main_views.handler404
handler500 = main_views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annunci/urls.py
from django.conf.urls import url
from . import views

app_name = 'annunci'

urlpatterns = [

    # /annunci/
    url(r'^$', views.lista_annunci, name='lista_annunci'),

    # /annunci/nuovo/
    url(r'nuovo/$', views.inserisci_annuncio, name='inserisci_annuncio'),

    # /annunci/#annuncio/dettagli/
    url(r'(?P<oid>[0-9]+)/dettagli/$', views.dettagli_annuncio, name='dettagli_annuncio'),

    # /annunci/#annuncio/modifica/
    url(r'(?P<oid>[0-9]+)/modifica/$', views.modifica_annuncio, name='modifica_annuncio'),

    # /annunci/#annuncio/elimina/
    url(r'(?P<oid>[0-9]+)/elimina/$', views.elimina_annuncio, name='elimina_annuncio'),

    # /annunci/#annuncio/elimina/conferma/
    url(r'(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_annuncio_conferma, name='elimina_annuncio_conferma'),

    # /annunci/#annuncio/accetta/
    url(r'(?P<oid>[0-9]+)/accetta/$', views.accetta_annuncio, name='accetta_annuncio'),

    # /annunci/#annuncio/accetta/conferma/
    url(r'(?P<oid>[0-9]+)/accetta/conferma/$', views.conferma_annuncio, name='conferma_annuncio'),

    # /annunci/calendario/
    url(r'calendario/$', views.calendario, name='calendario'),

    # /annunci/@username/elenco
    url(r'(?P<username>\w+)/elenco/$', views.annunci_di_utente, name='annunci_di_utente'),
]

recensioni/urls.py
from django.conf.urls import url
from . import views

app_name = 'recensioni'

urlpatterns = [

    # /recensioni/nuova/#user_recensito/
    url(r'nuova/(?P<oid>[0-9]+)/$', views.nuova_recensione, name='nuova_recensione'),

    # /recensioni/ricevute/@username/
    url(r'ricevute/(?P<username>\w+)/$', views.recensioni_ricevute, name='recensioni_ricevute'),
]

utenti/urls.py
from django.conf.urls import url
from . import views

app_name = 'utenti'

urlpatterns = [

    # /utenti/login/
    url(r'login/$', views.login_user, name='utenti_login'),

    # /utenti/registrazione/
    url(r'registrazione/$', views.registrazione, name='registrazione'),

    # /utenti/registrazione/normale
    url(r'registrazione/normale$', views.registrazione_normale, name='registrazione_normale'),

    # /utenti/registrazione/petsitter
    url(r'registrazione/petsitter$', views.registrazione_petsitter, name='registrazione_petsitter'),

    # /utenti/logout/
    url(r'logout/$', views.logout_user, name='utenti_logout'),

    # /utenti/profilo/#user
    url(r'profilo/(?P<oid>[0-9]+)/$', views.view_profile, name='view_profile'),

    # /utenti/profilo/#user/modifica/
    url(r'profilo/(?P<oid>[0-9]+)/modifica/$', views.edit_profile, name='edit_profile'),

    # /utenti/profilo/#user/elimina/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/$', views.elimina_profilo, name='elimina_profilo'),

    # /utenti/profilo/#user/elimina/conferma/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_profilo_conferma, name='elimina_profilo_conferma'),

    # /utenti/cassa/
    url(r'cassa/$', views.cassa, name='cassa'),

    # /utenti/classifica/
    url(r'classifica/$', views.classifica, name='classifica'),

    # /utenti/cerca/
    url(r'cerca/$', views.cerca_utenti, name='cerca_utenti'),

    # /check_username/?username=john
    url(r'check_username/$', views.check_username, name='check_username'),

    # /utenti/scegli_profilo/
    url(r'scegli_profilo/$', views.scelta_profilo_oauth, name='scelta_profilo_oauth'),

    # /utenti/oauth_petsitter
    url(r'oauth_petsitter/$', views.oauth_petsitter, name='oauth_petsitter'),

    # /utenti/oauth_normale
    url(r'oauth_normale/$', views.oauth_normale, name='oauth_normale'),
]

utenti/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    indirizzo = models.CharField(max_length=100)
    citta = models.CharField(max_length=50)
    provincia = models.CharField(max_length=2)
    regione = models.CharField(max_length=50)
    latitudine = models.FloatField(null=True, default=0, blank=True)
    longitudine = models.FloatField(null=True, default=0, blank=True)
    telefono = models.CharField(max_length=20)
    pet_coins = models.IntegerField(default=0)
    foto_profilo = models.FileField(null=True, default='', blank=True)

    pet_sitter = models.BooleanField(default=False)

    nome_pet = models.CharField(max_length=50, default="", null=True)
    pet = models.CharField(max_length=50, default="", null=True)
    razza = models.CharField(max_length=50, default="", null=True)
    eta = models.PositiveIntegerField(null=True)                   # età del pet
    caratteristiche = models.CharField(max_length=250, default="", null=True)
    foto_pet = models.FileField(null=True, default='', blank=True)

    descrizione = models.CharField(max_length=250, default="", null=True)
    hobby = models.CharField(max_length=100, default="", null=True)

    def __str__(self):
        return self.user.username

    def foto_profilo_or_default(self, default_path=static("/images/user_default.jpg")):
        if self.foto_profilo:
            return settings.MEDIA_URL + str(self.foto_profilo)
        return default_path

    def foto_pet_or_default(self, default_path=static("/images/pet_default.jpg")):
        if self.foto_pet:
            return settings.MEDIA_URL + str(self.foto_pet)
        return default_path

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

utenti/templates/utenti/base_registrazione.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

{% for field in profileForm %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

utenti/templates/utenti/elimina_profilo.html
{% extends base_template %}
{% block title %}Animal'sCare - Elimina profilo{% endblock %}
{% block annunci_active %}active{% endblock %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h3>Attenzione, azione potenzialmente pericolosa.</h3><br>
                        <h4>Confermi di voler eliminare il tuo profilo e
                            tutti gli annunci e i dati ad esso associati?</h4><br>

                        <a href="{% url 'utenti:view_profile' oid=user.pk %}" class="btn btn-primary">Indietro</a>&nbsp;&nbsp;
                        <a href="{% url 'utenti:elimina_profilo_conferma' oid=user.pk %}" class="btn btn-danger">
                            Conferma</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

utenti/templates/utenti/profilo_normale.html
{% extends base_template %}
{% load staticfiles%}
{% block title %}Animal'sCare - Profilo{% endblock %}
{% block profilo_active %}active{% endblock %}


{% block body %}

<script type="text/javascript" src="{% static 'map.js' %}"></script>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-8 toppad" style="float: none; margin: 0 auto;">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ view_user.username }} - utente normale</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3 col-lg-3 " align="center"><img alt="Foto profilo"
                                src="{{ user_profile.foto_profilo_or_default }}" class="img-responsive"></div>

                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Nome</td>
                                        <td>{{ view_user.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Cognome</td>
                                        <td>{{ view_user.last_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td><a href="mailto:{{ view_user.email }}">{{ view_user.email }}</a></td>
                                    </tr>
                                    <tr>
                                        <td>Indirizzo</td>
                                        <td>{{ user_profile.indirizzo }}</td>
                                    </tr>
                                    <tr>
                                        <td>Città</td>
                                        <td>{{ user_profile.citta }}</td>
                                    </tr>
                                    <tr>
                                        <td>Provincia</td>
                                        <td>{{ user_profile.provincia }}</td>
                                    </tr>
                                    <tr>
                                        <td>Regione</td>
                                        <td>{{ user_profile.regione }}</td>
                                    </tr>
                                    <tr>
                                        <td>Posizione</td>
                                        <td>
                                            <input id="mappa-btn" type="button" onclick="myFunction()"
                                                   value="Mostra mappa">
                                            <div id="mappa-div" style="display: none">
                                                <iframe width="300" height="250" frameborder="0" style="border:0"
                                                        src="https://www.google.com/maps/embed/v1/search?q=
                                                        {{ user_profile.indirizzo }}%20{{ user_profile.citta }}%20
                                                        {{ user_profile.provincia }}%20{{ user_profile.regione }}
                                                        &key=AIzaSyA6GQs9IyXUWEBu6vDvlKteuM0AReR4Nag"
                                                        allowfullscreen></iframe>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Telefono</td>
                                        <td>{{ user_profile.telefono }}</td>
                                    </tr>
                                    <tr>
                                        <td>Voti</td>
                                        <td>
                                            {% for i in 'xxxxx' %}
                                                {% if forloop.counter0 < voto_avg %}
                                                    <span class="glyphicon glyphicon-heart"></span>
                                                {% else %}
                                                    <span class="glyphicon glyphicon-heart-empty"></span>
                                                {% endif %}
                                            {% endfor %}
                                            ( {{ voto_avg }})
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Recensioni</td>
                                        <td>
                                            <span class="glyphicon glyphicon-comment"></span>(
                                                {{ recensioni_num }}
                                            {% if recensioni_num != 1 %}
                                                Recensioni
                                            {% else %}
                                                Recensione
                                            {% endif %}
                                            )</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-3 col-lg-3 " align="left"><img alt = "Foto pet"
                                                                          src="{{ user_profile.foto_pet_or_default }}"
                                                                            class="img-responsive"></div>
                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Nome pet</td>
                                        <td>{{ user_profile.nome_pet }}</td>
                                    </tr>
                                    <tr>
                                        <td>Razza</td>
                                        <td>{{ user_profile.razza }}</td>
                                    </tr>
                                    <tr>
                                        <td>Età pet</td>
                                        <td>{{ user_profile.eta }}</td>
                                    </tr>
                                    <tr>
                                        <td>Particolarità</td>
                                        <td>{{ user_profile.caratteristiche }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a href="{% url 'annunci:annunci_di_utente' username=view_user.username %}"
                       class="btn btn-primary">Annunci di {{ view_user.username }}</a>
                    <a href="{% url 'recensioni:recensioni_ricevute' username=view_user.username %}"
                       class="btn btn-primary">Recensioni ricevute</a>
                    {% if request.user.pk == view_user.pk %}
                        <span class="pull-right">
                            <a href="{% url 'utenti:edit_profile' oid=user.pk %}" class="btn btn-primary">
                                Modifica profilo</a>
                            <a href="{% url 'utenti:elimina_profilo' oid=user.pk %}" class="btn btn-danger">
                                Elimina profilo</a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

utenti/templates/utenti/profilo_petsitter.html
{% extends base_template %}
{% load staticfiles%}
{% block title %}Animal'sCare - Profilo{% endblock %}
{% block profilo_active %}active{% endblock %}


{% block body %}

<script type="text/javascript" src="{% static 'map.js' %}"></script>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-8 toppad" style="float: none; margin: 0 auto;">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ view_user.username }} - petsitter</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3 col-lg-3 " align="center"><img alt="Foto profilo"
                                src="{{ user_profile.foto_profilo_or_default }}" class="img-responsive"></div>

                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Nome</td>
                                        <td>{{ view_user.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Cognome</td>
                                        <td>{{ view_user.last_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td><a href="mailto:{{ view_user.email }}">{{ view_user.email }}</a></td>
                                    </tr>
                                    <tr>
                                        <td>Indirizzo</td>
                                        <td>{{ user_profile.indirizzo }}</td>
                                    </tr>
                                    <tr>
                                        <td>Città</td>
                                        <td>{{ user_profile.citta }}</td>
                                    </tr>
                                    <tr>
                                        <td>Provincia</td>
                                        <td>{{ user_profile.provincia }}</td>
                                    </tr>
                                    <tr>
                                        <td>Regione</td>
                                        <td>{{ user_profile.regione }}</td>
                                    </tr>
                                    <tr>
                                        <td>Posizione</td>
                                        <td>
                                            <input id="mappa-btn" type="button" onclick="myFunction()"
                                                   value="Mostra mappa">
                                            <div id="mappa-div" style="display: none">
                                                <iframe width="300" height="250" frameborder="0" style="border:0"
                                                        src="https://www.google.com/maps/embed/v1/search?q=
                                                        {{ user_profile.indirizzo }}%20{{ user_profile.citta }}%20
                                                        {{ user_profile.provincia }}%20{{ user_profile.regione }}
                                                        &key=AIzaSyA6GQs9IyXUWEBu6vDvlKteuM0AReR4Nag"
                                                        allowfullscreen></iframe>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Telefono</td>
                                        <td>{{ user_profile.telefono }}</td>
                                    </tr>
                                    <tr>
                                        <td>Descrizione</td>
                                        <td>{{ user_profile.descrizione }}</td>
                                    </tr>
                                    <tr>
                                        <td>Hobby</td>
                                        <td>{{ user_profile.hobby }}</td>
                                    </tr>
                                    <tr>
                                        <td>Voti</td>
                                        <td>
                                            {% for i in 'xxxxx' %}
                                                {% if forloop.counter0 < voto_avg %}
                                                    <span class="glyphicon glyphicon-heart"></span>
                                                {% else %}
                                                    <span class="glyphicon glyphicon-heart-empty"></span>
                                                {% endif %}
                                            {% endfor %}
                                            ( {{ voto_avg }})
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Recensioni</td>
                                        <td>
                                            <span class="glyphicon glyphicon-comment"></span>(
                                                {{ recensioni_num }}
                                            {% if recensioni_num != 1 %}
                                                Recensioni
                                            {% else %}
                                                Recensione
                                            {% endif %}
                                            )</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a href="{% url 'annunci:annunci_di_utente' username=view_user.username %}"
                       class="btn btn-primary">Visualizza annunci di {{ view_user.username }}</a>
                    <a href="{% url 'recensioni:recensioni_ricevute' username=view_user.username %}"
                       class="btn btn-primary">Recensioni ricevute</a>
                    {% if request.user.pk == view_user.pk %}
                        <span class="pull-right">
                            <a href="{% url 'utenti:edit_profile' oid=view_user.pk %}" class="btn btn-primary">
                                Modifica profilo</a>
                        <a href="{% url 'utenti:elimina_profilo' oid=user.pk %}" class="btn btn-danger">
                            Elimina profilo</a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

utenti/templates/utenti/registrazione.html
{% extends base_template %}
{% block title %}Animal'sCare - Registrazione{% endblock %}
{% block login_active %}active{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h3>Registra un account</h3>
                    </div>
                    <br>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <div class="col-sm-offset-20 col-sm-100">
                        <ul>
                            <li>
                                Registra un <a href="{% url 'utenti:registrazione_normale' %}">account normale</a><br>
                            </li>
                            <li>
                                Registra un <a href="{% url 'utenti:registrazione_petsitter' %}">account da pet sitter</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="panel-footer">
                    Hai già un account? <a href="{% url 'utenti:utenti_login' %}">Clicca qui</a> per fare il log in.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

utenti/templates/utenti/scelta_utente_oauth.html
{% extends base_template %}
{% load staticfiles%}
{% block title %}Animal'sCare - scegli qui come vuoi completare la tua registrazione{% endblock %}
{% block login_active %}active{% endblock %}


{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h3>Scegli il tipo di profilo</h3>
                    </div>
                    <br>
                    <div class="col-sm-offset-20 col-sm-100">
                        <br>
                        <button><a href="{% url 'utenti:oauth_normale'%}">Utente Normale</a></button>
                        <br><br>
                        <button><a href="{% url 'utenti:oauth_petsitter'%}">PetSitter</a></button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock body %}