API/urls.py
from django.conf.urls import url
from . import views

app_name = 'API'

urlpatterns = [

    # prende le informazioni di un utente
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET
    url(r'utenti/profilo/(?P<pk>[0-9]+)/$', views.userInfoLogin.as_view(), name='API-user-info'),

    # prende le informazioni dell'utente che ha richiamato l'api e ne permette la modifica
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET / PUT - serve essere loggati
    url(r'utenti/profilo/$', views.selfUserInfoLogin.as_view(), name='API-self-user-info'),

    # completa la registrazione per un petsitter
    # /API/utenti/registra/petsitter metodi ammessi :PUT
    url(r'utenti/registra/petsitter$', views.completaRegPetsitter.as_view(), name='API-registra-petsitter'),

    # completa la registrazione per un utente normale
    # /API/utenti/registra/utente-normale metodi ammessi :PUT
    url(r'utenti/registra/utente-normale$', views.completaRegUtentenormale.as_view(),
        name='API-registra-utente-normale'),

    # visualizza gli annunci
    # /API/annunci/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/$', views.listaAnnunci.as_view(), name='API-lista-annunci'),

    # filtra gli annunci
    # /API/annunci/filtra-per-dist-decrescente/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/ordina/(?P<animale>[A-Za-z0-9*èòàùì]+)/(?P<ordinamento>[A-Za-z0-9*èòàùì]+)/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/$',
        views.ordinaAnnunci.as_view(),
        name='API-ordina-annunci-animale-distanza-utente'),

    # osserva l'annuncio nel dettaglio e ne permette anche l'eliminazione o modifica purchè chi la chiama è
    # colui che lo ha scritto
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/dettagli/$', views.dettaglioAnnuncio.as_view(), name='API-dettaglio-annuncio'),

    # restituisce solamente gli annunci di un utente avente un determinato ID
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/(?P<pk>[0-9]+)/elenco/$', views.elencoAnnunciUtente.as_view(), name='API-elenco-annunci-utente'),

    # inserisce un nuovo annuncio
    # /API/annunci/nuovo/
    url(r'annunci/nuovo/$', views.inserisciAnnuncio.as_view(), name='API-nuovo-annuncio'),

    # accetta un annuncio avente ID comunicato via link
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/accetta/$', views.accettaAnnuncio.as_view(), name='API-accetta-annuncio'),

    # restituisce gli annunci accettati dall'utente che richiama questo link
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/$', views.calendarioUtente.as_view(), name='API-calendario-utente'),

    # restituisce gli annunci accettati dall'utente che richiama questo link filtrati per animale e validità
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/filtra/(?P<animale>[A-Za-z0-9*]+)/$',
        views.calendarioUtenteConFiltro.as_view(),
        name='API-calendario-utente-con-filtro-annunci'),

    # cerca l'utente per username
    # /API/utenti/cerca/<char:name>' GET : tutti gli utenti
    url(r'utenti/cerca/(?P<name>[A-Za-z0-9èòàùì]+)/$', views.cercaUtente.as_view(), name='API-cerca-utente'),

    # classifica utenti
    # /API/utenti/classifica/<tipo utente>/<criterio>/  metodi ammessi  GET : a tutti gli utenti
    url(r'utenti/classifica/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/(?P<criterio>[A-Za-z0-9èòàùì]+)/$',
        views.classificaUtenti.as_view(),
        name='API-classifica-utenti'),

    # Cassa Pet Coins utenti
    # /API/utenti/cassa/  metodi ammessi  PUT : ai soli utenti loggati
    url(r'utenti/cassa/$',
        views.modificaPetCoins.as_view(),
        name='API-petcoins-utenti'),

    # recensisci utenti
    # recensioni/nuova/<utente_recensito>/ metodi ammessi  POST : a tutti gli utenti
    # in automatico verrà settato il nickname di chi scrive la recensione
    url(r'recensioni/nuova/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensisciUtente.as_view(),
        name='API-recensisci-utenti'),

    # recensioni di un utente
    # /API/recensioni/ricevute/<utente>/  metodi ammessi  GET : a tutti gli utenti
    url(r'recensioni/ricevute/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensioniRicevute.as_view(),
        name='API-lista-recensioni-utente'),

    # contattaci
    # /API/annunci/nuovo/ metodi ammessi  POST : a tutti gli utenti loggati
    url(r'contattaci/$', views.contattaciInPrivato.as_view(), name='API-contattaci'),
]

Animal'sCare/urls.py
from main import views as main_views
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^annunci/', include('annunci.urls')),
    url(r'^contattaci/', include('contattaci.urls')),
    url(r'^utenti/', include('utenti.urls')),
    url(r'^recensioni/', include('recensioni.urls')),
    url(r'^api/', include('API.urls')),
    url('', include('social_django.urls', namespace='social')),

    url("api-auth/", include("rest_framework.urls")),
    url("api/rest-auth/", include("rest_auth.urls")),
    url("api/rest-auth/registration/", include("rest_auth.registration.urls")),

    # url('accounts/', include('allauth.urls')), # <--
]

handler404 = main_views.handler404
handler500 = main_views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annunci/urls.py
from django.conf.urls import url
from . import views

app_name = 'annunci'

urlpatterns = [

    # /annunci/
    url(r'^$', views.lista_annunci, name='lista_annunci'),

    # /annunci/nuovo/
    url(r'nuovo/$', views.inserisci_annuncio, name='inserisci_annuncio'),

    # /annunci/#annuncio/dettagli/
    url(r'(?P<oid>[0-9]+)/dettagli/$', views.dettagli_annuncio, name='dettagli_annuncio'),

    # /annunci/#annuncio/modifica/
    url(r'(?P<oid>[0-9]+)/modifica/$', views.modifica_annuncio, name='modifica_annuncio'),

    # /annunci/#annuncio/elimina/
    url(r'(?P<oid>[0-9]+)/elimina/$', views.elimina_annuncio, name='elimina_annuncio'),

    # /annunci/#annuncio/elimina/conferma/
    url(r'(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_annuncio_conferma, name='elimina_annuncio_conferma'),

    # /annunci/#annuncio/accetta/
    url(r'(?P<oid>[0-9]+)/accetta/$', views.accetta_annuncio, name='accetta_annuncio'),

    # /annunci/#annuncio/accetta/conferma/
    url(r'(?P<oid>[0-9]+)/accetta/conferma/$', views.conferma_annuncio, name='conferma_annuncio'),

    # /annunci/calendario/
    url(r'calendario/$', views.calendario, name='calendario'),

    # /annunci/@username/elenco
    url(r'(?P<username>\w+)/elenco/$', views.annunci_di_utente, name='annunci_di_utente'),
]

contattaci/urls.py
from django.conf.urls import url
from . import views

app_name = 'contattaci'

urlpatterns = [

    # /contattaci/
    url(r'^$', views.contattaci, name='contattaci'),
]

contattaci/forms.py
from django import forms
import re
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class ContattaciForm(forms.Form):
    required_css_class = 'required'
    titolo = forms.CharField()
    messaggio = forms.CharField(widget=forms.Textarea)

    class Meta:
        fields = ['titolo', 'messaggio']

    def clean_titolo(self):
        if not re.match("^[A-Za-z0-9 .,'èòàùì]+$", self.cleaned_data['titolo']):
            raise ValidationError(_('Errore: il titolo può contenere solo lettere, numeri e spazi.'))
        if not (1 <= len(self.cleaned_data['titolo']) <= 95):
            raise ValidationError(_('Errore: il titolo deve avere lunghezza fra 1 e 95 caratteri.'))
        return self.cleaned_data['titolo']

    def clean_messaggio(self):
        if not re.match("^[A-Za-z0-9 .,'èòàùì!?]+$", self.cleaned_data['messaggio']):
            raise ValidationError(_('Errore: il messaggio può contenere solo lettere, numeri e spazi.'))
        if not (1 <= len(self.cleaned_data['messaggio']) <= 300):
            raise ValidationError(_('Errore: il messaggio deve avere lunghezza fra 1 e 300 caratteri.'))
        return self.cleaned_data['messaggio']

contattaci/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from utenti.models import Profile
from django.shortcuts import render
from django.core.urlresolvers import reverse
from .forms import ContattaciForm
from django.core.mail import EmailMessage
from django.conf import settings
from main.views import nega_accesso_senza_profilo


@login_required(login_url='/utenti/login/')
def contattaci(request):
    """
    Permette all'utente di contattare gli amministratori del sito scrivendo un titolo e un messaggio.
    Il messaggio viene recapitato alla mailbox del sito, con mittente la mailbox del sito stessa.
    Nel corpo della mail viene inserito lo username dell'utente così che i messaggi non siano anonimi.

    :param request: request utente.
    :return: render pagina contattaci.
    """

    if nega_accesso_senza_profilo(request):
        return HttpResponseRedirect(reverse('utenti:scelta_profilo_oauth'))

    form = ContattaciForm(request.POST or None)

    context = {
        "form": form,
        "base_template": 'main/base.html'
    }

    if form.is_valid():
        # manda email
        email = EmailMessage(form.cleaned_data['titolo'],
                             'Messaggio dall\'utente: ' + request.user.username + "\n" +
                             form.cleaned_data['messaggio'], to=[settings.EMAIL_HOST_USER])
        email.send()
        return render(request, 'success.html', context)

    context.update({'user_profile': Profile.objects.filter(user=request.user).first()})

    return render(request, 'contattaci.html', context)

contattaci/templates/contattaci.html
{% extends base_template %}
{% load staticfiles%}
{% block title %}Animal'sCare - Contattaci{% endblock %}
{% block contattaci_active %}active{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="text-align: center;">
                        <h3>Contattaci</h3>
                    </div>
                    </br>
                    <form id="contattaci-form" class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Invia messaggio</button>
                            </div>
                        </div>
                    </form>
                    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                    <script type="text/javascript" src="{% static 'contattaci_form_validator.js' %}"></script>

                    </br>
                    <p> I campi contrassegnati con <span style="color:red;">*</span> sono obbligatori.</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

contattaci/templates/success.html
{% extends base_template %}
{% load staticfiles%}
{% block title %}Animal'sCare - Contattaci{% endblock %}
{% block contattaci_active %}active{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6" style="float: none; margin: 0 auto;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p><strong>Messaggio inviato con successo.</strong></p>
                    Sarai reindirizzato all'elenco annunci in <span id="countdown">5</span> secondi.

                    <script>
                        var seconds = document.getElementById("countdown").textContent;
                        var countdown = setInterval(function() {
                            seconds--;
                            document.getElementById("countdown").textContent = seconds;
                            if (seconds <= 0) clearInterval(countdown);
                        }, 1000);
                        window.setTimeout(function(){
                            window.location.href = "{% url 'annunci:lista_annunci' %}";
                        }, 5000);
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}