API/urls.py
from django.conf.urls import url
from . import views

app_name = 'API'

urlpatterns = [

    # prende le informazioni di un utente
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET
    url(r'utenti/profilo/(?P<pk>[0-9]+)/$', views.userInfoLogin.as_view(), name='API-user-info'),

    # prende le informazioni dell'utente che ha richiamato l'api e ne permette la modifica
    # /API/utenti/profilo/<int:oid> metodi ammessi :GET / PUT - serve essere loggati
    url(r'utenti/profilo/$', views.selfUserInfoLogin.as_view(), name='API-self-user-info'),

    # completa la registrazione per un petsitter
    # /API/utenti/registra/petsitter metodi ammessi :PUT
    url(r'utenti/registra/petsitter$', views.completaRegPetsitter.as_view(), name='API-registra-petsitter'),

    # completa la registrazione per un utente normale
    # /API/utenti/registra/utente-normale metodi ammessi :PUT
    url(r'utenti/registra/utente-normale$', views.completaRegUtentenormale.as_view(),
        name='API-registra-utente-normale'),

    # visualizza gli annunci
    # /API/annunci/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/$', views.listaAnnunci.as_view(), name='API-lista-annunci'),

    # filtra gli annunci
    # /API/annunci/filtra-per-dist-decrescente/  metodi ammessi  GET : a tutti gli utenti
    url(r'annunci/ordina/(?P<animale>[A-Za-z0-9*èòàùì]+)/(?P<ordinamento>[A-Za-z0-9*èòàùì]+)/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/$',
        views.ordinaAnnunci.as_view(),
        name='API-ordina-annunci-animale-distanza-utente'),

    # osserva l'annuncio nel dettaglio e ne permette anche l'eliminazione o modifica purchè chi la chiama è
    # colui che lo ha scritto
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/dettagli/$', views.dettaglioAnnuncio.as_view(), name='API-dettaglio-annuncio'),

    # restituisce solamente gli annunci di un utente avente un determinato ID
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/(?P<pk>[0-9]+)/elenco/$', views.elencoAnnunciUtente.as_view(), name='API-elenco-annunci-utente'),

    # inserisce un nuovo annuncio
    # /API/annunci/nuovo/
    url(r'annunci/nuovo/$', views.inserisciAnnuncio.as_view(), name='API-nuovo-annuncio'),

    # accetta un annuncio avente ID comunicato via link
    # /API/annunci/<int:oid>/dettagli' GET : a tutti gli utenti | POST/PUT/DELETE solo ai proprietari
    url(r'annunci/(?P<pk>[0-9]+)/accetta/$', views.accettaAnnuncio.as_view(), name='API-accetta-annuncio'),

    # restituisce gli annunci accettati dall'utente che richiama questo link
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/$', views.calendarioUtente.as_view(), name='API-calendario-utente'),

    # restituisce gli annunci accettati dall'utente che richiama questo link filtrati per animale e validità
    # /API/annunci/<int:oid>/elenco' GET : a tutti gli utenti
    url(r'annunci/calendario/filtra/(?P<animale>[A-Za-z0-9*]+)/$',
        views.calendarioUtenteConFiltro.as_view(),
        name='API-calendario-utente-con-filtro-annunci'),

    # cerca l'utente per username
    # /API/utenti/cerca/<char:name>' GET : tutti gli utenti
    url(r'utenti/cerca/(?P<name>[A-Za-z0-9èòàùì]+)/$', views.cercaUtente.as_view(), name='API-cerca-utente'),

    # classifica utenti
    # /API/utenti/classifica/<tipo utente>/<criterio>/  metodi ammessi  GET : a tutti gli utenti
    url(r'utenti/classifica/(?P<tipo_utente>[A-Za-z0-9*èòàùì]+)/(?P<criterio>[A-Za-z0-9èòàùì]+)/$',
        views.classificaUtenti.as_view(),
        name='API-classifica-utenti'),

    # Cassa Pet Coins utenti
    # /API/utenti/cassa/  metodi ammessi  PUT : ai soli utenti loggati
    url(r'utenti/cassa/$',
        views.modificaPetCoins.as_view(),
        name='API-petcoins-utenti'),

    # recensisci utenti
    # recensioni/nuova/<utente_recensito>/ metodi ammessi  POST : a tutti gli utenti
    # in automatico verrà settato il nickname di chi scrive la recensione
    url(r'recensioni/nuova/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensisciUtente.as_view(),
        name='API-recensisci-utenti'),

    # recensioni di un utente
    # /API/recensioni/ricevute/<utente>/  metodi ammessi  GET : a tutti gli utenti
    url(r'recensioni/ricevute/(?P<utente>[A-Za-z0-9èòàùì]+)/$',
        views.recensioniRicevute.as_view(),
        name='API-lista-recensioni-utente'),

    # contattaci
    # /API/annunci/nuovo/ metodi ammessi  POST : a tutti gli utenti loggati
    url(r'contattaci/$', views.contattaciInPrivato.as_view(), name='API-contattaci'),
]

Animal'sCare/urls.py
from main import views as main_views
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^annunci/', include('annunci.urls')),
    url(r'^contattaci/', include('contattaci.urls')),
    url(r'^utenti/', include('utenti.urls')),
    url(r'^recensioni/', include('recensioni.urls')),
    url(r'^api/', include('API.urls')),
    url('', include('social_django.urls', namespace='social')),

    url("api-auth/", include("rest_framework.urls")),
    url("api/rest-auth/", include("rest_auth.urls")),
    url("api/rest-auth/registration/", include("rest_auth.registration.urls")),

    # url('accounts/', include('allauth.urls')), # <--
]

handler404 = main_views.handler404
handler500 = main_views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annunci/urls.py
from django.conf.urls import url
from . import views

app_name = 'annunci'

urlpatterns = [

    # /annunci/
    url(r'^$', views.lista_annunci, name='lista_annunci'),

    # /annunci/nuovo/
    url(r'nuovo/$', views.inserisci_annuncio, name='inserisci_annuncio'),

    # /annunci/#annuncio/dettagli/
    url(r'(?P<oid>[0-9]+)/dettagli/$', views.dettagli_annuncio, name='dettagli_annuncio'),

    # /annunci/#annuncio/modifica/
    url(r'(?P<oid>[0-9]+)/modifica/$', views.modifica_annuncio, name='modifica_annuncio'),

    # /annunci/#annuncio/elimina/
    url(r'(?P<oid>[0-9]+)/elimina/$', views.elimina_annuncio, name='elimina_annuncio'),

    # /annunci/#annuncio/elimina/conferma/
    url(r'(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_annuncio_conferma, name='elimina_annuncio_conferma'),

    # /annunci/#annuncio/accetta/
    url(r'(?P<oid>[0-9]+)/accetta/$', views.accetta_annuncio, name='accetta_annuncio'),

    # /annunci/#annuncio/accetta/conferma/
    url(r'(?P<oid>[0-9]+)/accetta/conferma/$', views.conferma_annuncio, name='conferma_annuncio'),

    # /annunci/calendario/
    url(r'calendario/$', views.calendario, name='calendario'),

    # /annunci/@username/elenco
    url(r'(?P<username>\w+)/elenco/$', views.annunci_di_utente, name='annunci_di_utente'),
]

contattaci/urls.py
from django.conf.urls import url
from . import views

app_name = 'contattaci'

urlpatterns = [

    # /contattaci/
    url(r'^$', views.contattaci, name='contattaci'),
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    # /main/
    url(r'^$', views.index, name='index'),

]

utenti/urls.py
from django.conf.urls import url
from . import views

app_name = 'utenti'

urlpatterns = [

    # /utenti/login/
    url(r'login/$', views.login_user, name='utenti_login'),

    # /utenti/registrazione/
    url(r'registrazione/$', views.registrazione, name='registrazione'),

    # /utenti/registrazione/normale
    url(r'registrazione/normale$', views.registrazione_normale, name='registrazione_normale'),

    # /utenti/registrazione/petsitter
    url(r'registrazione/petsitter$', views.registrazione_petsitter, name='registrazione_petsitter'),

    # /utenti/logout/
    url(r'logout/$', views.logout_user, name='utenti_logout'),

    # /utenti/profilo/#user
    url(r'profilo/(?P<oid>[0-9]+)/$', views.view_profile, name='view_profile'),

    # /utenti/profilo/#user/modifica/
    url(r'profilo/(?P<oid>[0-9]+)/modifica/$', views.edit_profile, name='edit_profile'),

    # /utenti/profilo/#user/elimina/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/$', views.elimina_profilo, name='elimina_profilo'),

    # /utenti/profilo/#user/elimina/conferma/
    url(r'profilo/(?P<oid>[0-9]+)/elimina/conferma/$', views.elimina_profilo_conferma, name='elimina_profilo_conferma'),

    # /utenti/cassa/
    url(r'cassa/$', views.cassa, name='cassa'),

    # /utenti/classifica/
    url(r'classifica/$', views.classifica, name='classifica'),

    # /utenti/cerca/
    url(r'cerca/$', views.cerca_utenti, name='cerca_utenti'),

    # /check_username/?username=john
    url(r'check_username/$', views.check_username, name='check_username'),

    # /utenti/scegli_profilo/
    url(r'scegli_profilo/$', views.scelta_profilo_oauth, name='scelta_profilo_oauth'),

    # /utenti/oauth_petsitter
    url(r'oauth_petsitter/$', views.oauth_petsitter, name='oauth_petsitter'),

    # /utenti/oauth_normale
    url(r'oauth_normale/$', views.oauth_normale, name='oauth_normale'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from utenti.models import Profile


def nega_accesso_senza_profilo(request):
    """
    Funzione utilizzata dalle view per negare l'accesso agli utenti oauth loggati e sprovvisti di un profilo
    (perchè non hanno completato la registrazione del proprio profilo).

    :param request: request utente.
    :return: render della pagina scelta_profilo_oauth.
    """

    # if request.user.is_authenticated:
    #     try:
    #         Profile.objects.get(user=request.user.id)
    #     except Exception:
    #         return True

    if request.user.is_authenticated:
        profilo = Profile.objects.get(user=request.user.id)
        if len(profilo.indirizzo) == 0:
            return True
    return False


def index(request):
    """
    Mostra la pagina principale del sito, lista annunci.

    :param request: request utente.
    :return: redirect alla view lista_annunci.
    """

    return HttpResponseRedirect(reverse('annunci:lista_annunci'))


def handler404(request):
    """
    Custom handler per errore 404.

    :param request: request utente.
    :return: redirect alla pagina errore 404.
    """

    if request.user.is_authenticated():
        context = ({'base_template': 'main/base.html'})
        context.update({'user_profile': Profile.objects.filter(user=request.user).first()})
    else:
        context = ({'base_template': 'main/base_visitor.html'})
    return render(request, '404.html', status=404, context=context)


def handler500(request):
    """
        Custom handler per errore 500.

        :param request: request utente.
        :return: redirect alla pagina errore 500.
        """

    if request.user.is_authenticated():
        context = ({'base_template': 'main/base.html'})
        context.update({'user_profile': Profile.objects.filter(user=request.user).first()})
    else:
        context = ({'base_template': 'main/base_visitor.html'})
    return render(request, '500.html', status=500, context=context)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Animal'sCare{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">Animal'sCare</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="{% block annunci_active %}{% endblock %}">
                    <a href="{% url 'main:index' %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Annunci
                    </a>
                </li>

                <li class="{% block inserisci_annuncio_active %}{% endblock %}">
                    <a href="{% url 'annunci:inserisci_annuncio' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Inserisci Annuncio
                    </a>
                </li>

                <li class="{% block classifica_active %}{% endblock %}">
                    <a href="{% url 'utenti:classifica' %}">
                        <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp; Classifica
                    </a>
                </li>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'utenti:cerca_utenti' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="cerca" value="" placeholder="Cerca username">
                </div>
                <button type="submit" class="btn btn-default">Cerca</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block profilo_active %}{% endblock %}">
                    <a href="{% url 'utenti:view_profile' oid=user.pk %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profilo
                    </a>
                </li>

                <li class="{% block calendario_active %}{% endblock %}">
                    <a href="{% url 'annunci:calendario' %}">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Calendario
                    </a>
                </li>

                <li class="{% block pet_coins_active %}{% endblock %}">
                    <a href="{% url 'utenti:cassa' %}" >
                        <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>&nbsp;
                            {{ user_profile.pet_coins }}&nbsp;
                            <img src="{% static 'images/pet_coin.png' %}" class="img-responsive"
                                       style="width: 18px; height: 18px; display: inline; margin-right: auto">
                    </a>
                </li>
                <li class="{% block contattaci_active %}{% endblock %}">
                    <a href="{% url 'contattaci:contattaci' %}">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp; Contattaci
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'utenti:utenti_logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<script>
    var selector = '.nav li';

    $(selector).on('click', function(){
        $(selector).removeClass('active');
        $(this).addClass('active');
    });
</script>

<footer class="footer">
  <div class="container" style="text-align: center; padding-top: 10px">
      <a href="{% url 'main:index' %}"><img style="margin-bottom: 4px" src="{% static 'favicon.ico' %}"  alt="Animal'sCare" height="18" width="18" /></a>&nbsp;
      <p class="text-muted" style="font-family: typold_medium, cursive; display: inline">
          BERSELLI, DI BLASI</p> <p class="text-muted" style="display: inline">- 2020</p>
  </div>
</footer>
</body>
</html>

main/templates/main/base_oauth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Animal'sCare{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">Animal'sCare</a>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<script>
    var selector = '.nav li';

    $(selector).on('click', function(){
        $(selector).removeClass('active');
        $(this).addClass('active');
    });
</script>

<footer class="footer">
  <div class="container" style="text-align: center; padding-top: 10px">
      <a href="{% url 'main:index' %}"><img style="margin-bottom: 4px" src="{% static 'favicon.ico' %}"  alt="Animal'sCare" height="18" width="18" /></a>&nbsp;
      <p class="text-muted" style="font-family: typold_medium, cursive; display: inline">
          BERSELLI, DI BLASI</p> <p class="text-muted" style="display: inline">- 2020</p>
  </div>
</footer>
</body>
</html>

main/templates/main/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Animal'sCare{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">Animal'sCare</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="{% block annunci_active %}{% endblock %}">
                    <a href="{% url 'main:index' %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Annunci
                    </a>
                </li>

                <li class="{% block classifica_active %}{% endblock %}">
                    <a href="{% url 'utenti:classifica' %}">
                        <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp; Classifica
                    </a>
                </li>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'utenti:cerca_utenti' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="cerca" value="" placeholder="Cerca username">
                </div>
                <button type="submit" class="btn btn-default">Cerca</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block login_active %}{% endblock %}">
                    <a href="{% url 'utenti:utenti-login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<footer class="footer">
  <div class="container" style="text-align: center; padding-top: 10px">
      <a href="{% url 'main:index' %}"><img style="margin-bottom: 4px" src="{% static 'favicon.ico' %}"  alt="Animal'sCare" height="18" width="18" /></a>&nbsp;
      <p class="text-muted" style="font-family: typold_medium, cursive; display: inline">
          BERSELLI, DI BLASI</p> <p class="text-muted" style="display: inline">- 2020</p>
  </div>
</footer>
</body>
</html>